config:
  lobby: true
  spawn: false
  
locations: 
  lobby: 
  spawn:
  
join: 
  effects: 
    lobby:
  
  messages:
    privatemsg: 
      on_leave: true
      on_join: true
    publicmsg: 
      on_leave: true
      on_join: true
    
